using Pkg
Pkg.activate(@__DIR__)
Pkg.develop(; path=joinpath(@__DIR__, "..", "..", ".."))

using LinearAlgebra, Mooncake, StableRNGs, Test
using Mooncake.TestUtils: TestCase, test_rule

sr(n::Int) = StableRNG(n)

_getter() = 5.0
@testset "array" begin
    test_cases = vcat(
        TestCase[
            TestCase(adjoint, randn(sr(1), 5); perf_flag=:allocs),
            TestCase(adjoint, randn(sr(2), 5, 4); perf_flag=:allocs),
            TestCase(*, 2.1, randn(sr(3), 2)),
            TestCase(*, -2.01, randn(sr(4), 1, 2)),
            TestCase(*, -0.5, randn(sr(5), 2, 2, 1)),
            TestCase(*, randn(sr(6), 2), 0.32),
            TestCase(*, randn(sr(7), 2, 1), 0.33),
            TestCase(*, randn(sr(8), 2, 1, 2), -0.34),
            TestCase(*, randn(sr(9), 2, 2), randn(sr(12), 2)),
            TestCase(*, randn(sr(10), 2, 2), randn(sr(11), 2, 3)),
            TestCase(*, 4.4, randn(sr(15), 3, 2), randn(sr(13), 2, 2), [-0.5, 0.1]),
            TestCase(*, 4.3, randn(sr(16), 2), adjoint(randn(sr(17), 2, 1))),
            TestCase(*, randn(sr(19)), randn(sr(20), 2), transpose(randn(sr(18), 2, 1))),
            TestCase(*, adjoint(randn(sr(22), 2, 2)), randn(sr(21), 2)),
            TestCase(*, Diagonal(randn(sr(23), 2)), randn(sr(24), 2)),
            TestCase(*, randn(sr(27), 2)', Diagonal(randn(sr(26), 2)), randn(sr(25), 2)),
            TestCase(*, randn(sr(28), 2, 3)', randn(sr(29), 2)),
            TestCase(*, 4.0 * I, randn(sr(30), 2)),
            TestCase(*, 3.5 * I, randn(sr(31), 2, 3)),
            TestCase(*, UpperTriangular(randn(sr(31), 2, 2)), randn(sr(32), 2)),
            TestCase(*, LowerTriangular(randn(sr(34), 2, 2)), randn(sr(33), 2)),
            TestCase(*, transpose(randn(sr(36), 2, 3)), randn(sr(35), 2)),
            TestCase(*, randn(sr(37), 2)', adjoint(randn(sr(38), 3, 2)), randn(sr(39), 3)),
            TestCase(
                *, randn(sr(42), 2)', transpose(randn(sr(41), 3, 2)), randn(sr(40), 3)
            ),
            TestCase(*, randn(sr(43), 1), transpose(randn(sr(44), 2, 1))),
            TestCase(
                *,
                transpose(randn(sr(47), 2, 3)),
                Diagonal(randn(sr(46), 2)),
                randn(sr(45), 2),
            ),
            TestCase(*, adjoint(randn(sr(46), 2, 3)), randn(sr(47), 2)),
            TestCase(*, transpose(randn(sr(49), 2, 3)), randn(sr(48), 2)),
            TestCase(
                *, adjoint(randn(sr(50), 2, 1)), randn(sr(51), 2, 3), randn(sr(52), 3)
            ),
            TestCase(
                *, transpose(randn(sr(55), 2, 1)), randn(sr(54), 2, 3), randn(sr(53), 3)
            ),
            TestCase(
                *,
                adjoint(randn(sr(55), 2, 1)),
                randn(sr(1), 2, 3),
                randn(sr(2), 3),
                randn(sr(3)),
            ),
            TestCase(
                *,
                transpose(randn(sr(4), 2, 1)),
                randn(sr(5), 2, 3),
                randn(sr(6), 3),
                randn(sr(7)),
            ),
            TestCase(
                *,
                adjoint(randn(sr(8), 2, 2)),
                randn(sr(9), 2, 3),
                randn(sr(10), 3, 2),
                randn(sr(11), 2),
            ),
            TestCase(
                *,
                transpose(randn(sr(1), 2, 2)),
                randn(sr(2), 2, 3),
                randn(sr(3), 3, 2),
                randn(sr(4), 2),
            ),
            TestCase(*, transpose(randn(sr(5), 2, 3)), randn(sr(6), 2)),
            TestCase(*, randn(sr(8), 1), adjoint(randn(sr(7), 2, 1))),
            TestCase(*, randn(sr(9), 1), transpose(randn(sr(0), 2, 1))),
            TestCase(*, randn(sr(3), 1), adjoint(randn(sr(2), 2, 1)), randn(sr(1), 2, 2)),
            TestCase(*, randn(sr(4), 1), transpose(randn(sr(5), 2, 1)), randn(sr(6), 2, 2)),
            TestCase(*, randn(sr(9), 1), adjoint(randn(sr(8), 2, 1)), randn(sr(7))),
            TestCase(*, randn(sr(0), 1), transpose(randn(sr(1), 2, 1)), randn(sr(2))),
            TestCase(*, randn(sr(4), 1), adjoint(randn(sr(3), 2, 1))),
            TestCase(*, randn(sr(5), 1), transpose(randn(sr(6), 2, 1))),
            TestCase(*, randn(sr(9), 3, 2), randn(sr(8), 2, 2), randn(sr(7), 2)),
            TestCase(*, randn(sr(0), 1), randn(sr(1), 1, 3)),
            TestCase(*, randn(sr(3), 3, 2), randn(sr(2), 2)),
            TestCase(*, randn(sr(4), 3, 2), randn(sr(5), 2), randn(sr(6))),
            TestCase(*, randn(sr(0), 3, 2), randn(sr(9), 2), randn(sr(8)), randn(sr(7))),
            TestCase(
                *, randn(sr(1), 2, 2), randn(sr(2), 2, 3), randn(sr(3), 3), randn(sr(4))
            ),
            TestCase(
                *,
                randn(sr(5), 2, 1),
                randn(sr(6), 1, 2),
                randn(sr(7), 2, 3),
                randn(sr(8), 3),
            ),
            TestCase(*, randn(sr(9), 2), 5.0 * I),
            TestCase(
                *,
                randn(sr(0)),
                adjoint(randn(sr(1), 2, 1)),
                randn(sr(2), 2, 3),
                randn(sr(3), 3),
            ),
            TestCase(
                *,
                randn(sr(4)),
                transpose(randn(sr(5), 2, 1)),
                randn(sr(6), 2, 3),
                randn(sr(7), 3),
            ),
            TestCase(*, randn(sr(8)), randn(sr(9)), randn(sr(0), 3, 2), randn(sr(1), 2)),
            TestCase(*, randn(sr(2), 2)', randn(sr(3), 2, 3), randn(sr(4), 3)),
            TestCase(+, randn(sr(5), 2), randn(sr(6), 2)),
            TestCase(+, randn(sr(7), 2), randn(sr(8), 2), randn(sr(9), 2), randn(sr(0), 2)),
            TestCase(-, randn(sr(1), 1, 2), randn(sr(2), 1, 2)),
            TestCase(-, randn(sr(3), 1, 2)),
            TestCase(/, randn(sr(6), 1, 2), 0.66),
            TestCase(/, randn(sr(7), 2), 5.0 * I),
            TestCase(/, randn(sr(8), 1), Diagonal(rand(sr(9), 1) .+ 1)),
            TestCase(/, randn(sr(0), 2, 2), Diagonal(rand(sr(1), 2) .+ 1)),
        ],
        map([
            rand(sr(1), 2, 2) + I,
            Bidiagonal(rand(sr(2), 3) .+ 1, [0.3, 0.6], 'L'),
            Bidiagonal(rand(sr(3), 3) .+ 1, [0.4, -0.3], 'U'),
            Diagonal(rand(sr(4), 2) .+ 1),
            LowerTriangular(randn(sr(5), 2, 2) + I),
            UpperTriangular(randn(sr(6), 2, 2) + I),
            UnitLowerTriangular(randn(sr(7), 2, 2)),
            UnitUpperTriangular(randn(sr(8), 2, 2)),
        ]) do X
            TestCase(/, randn(sr(1), 2, size(X, 1)), X)
        end,
        TestCase[
            TestCase(//, [1, 2], 5),
            TestCase(==, randn(sr(1), 1, 2), randn(2, 1); perf_flag=:allocs),
            TestCase(Array, randn(sr(2), 1, 2)),
            TestCase(Bidiagonal, randn(sr(3), 4), randn(sr(4), 3), 'L'; perf_flag=:allocs),
            TestCase(CartesianIndices, [1, 2, 3]; perf_flag=:allocs),
            TestCase(Diagonal, randn(sr(5), 4); perf_flag=:allocs),
            TestCase(IndexStyle, randn(sr(6), 1, 2)),
            TestCase(IndexStyle, randn(sr(7), 2, 1), randn(sr(8), 1, 2)),
            TestCase(LinearIndices, randn(sr(9), 3)),
            TestCase(LinearIndices, randn(sr(0), 3, 2)),
            TestCase(PermutedDimsArray, randn(sr(1), 2, 3), [2, 1]),
            TestCase(SubArray, randn(sr(2), 2, 3), (1:2, 2:3)),
            TestCase(\, 0.67, randn(sr(3), 2, 2)),
            TestCase(\, 3.0 * I, randn(sr(4), 2)),
            TestCase(\, 3.0 * I, randn(sr(5), 2, 1)),
            TestCase(\, UnitLowerTriangular(randn(sr(6), 2, 2)), randn(sr(7), 2)),
            TestCase(\, UnitUpperTriangular(randn(sr(9), 2, 2)), randn(sr(8), 2)),
            TestCase(
                (A, x) -> cholesky(A)' \ x,
                Symmetric(randn(sr(0), 2, 2) + 5I),
                randn(sr(1), 2),
            ),
            TestCase(
                (A, X) -> cholesky(A)' \ X,
                Symmetric(randn(sr(2), 2, 2) + 5I),
                randn(sr(3), 2, 3),
            ),
            TestCase(
                \,
                adjoint(Bidiagonal(rand(sr(4), 3) .+ 1, randn(sr(5), 2), 'U')),
                randn(sr(6), 3),
            ),
            TestCase(
                \,
                adjoint(Bidiagonal(rand(sr(8), 3) .+ 1, randn(sr(9), 2), 'U')),
                randn(sr(7), 3, 2),
            ),
            TestCase(
                \,
                adjoint(Bidiagonal(rand(sr(9), 3) .+ 1, randn(sr(0), 2), 'L')),
                randn(sr(8), 3),
            ),
            TestCase(
                \,
                adjoint(Bidiagonal(rand(sr(0), 3) .+ 1, randn(sr(1), 2), 'L')),
                randn(sr(9), 3, 2),
            ),
            TestCase(\, randn(sr(2), 2), randn(sr(3), 2, 2)),
            TestCase(\, LowerTriangular(rand(sr(4), 2, 2) + 3I), randn(sr(5), 2)),
            TestCase(\, UpperTriangular(rand(sr(7), 2, 2) + 3I), randn(sr(6), 2)),
            TestCase(\, Diagonal(rand(sr(9), 2) .+ 1), randn(sr(8), 2)),
            TestCase(
                \, Bidiagonal(rand(sr(0), 3) .+ 1, randn(sr(1), 2), 'U'), randn(sr(2), 3)
            ),
            TestCase(
                \, Bidiagonal(rand(sr(4), 3) .+ 1, randn(sr(5), 2), 'U'), randn(sr(6), 3, 2)
            ),
            TestCase(
                \, Bidiagonal(rand(sr(7), 3) .+ 1, randn(sr(8), 2), 'L'), randn(sr(9), 3)
            ),
            TestCase(
                \, Bidiagonal(rand(sr(1), 3) .+ 1, randn(sr(2), 2), 'L'), randn(sr(0), 3, 2)
            ),
            TestCase(\, rand(sr(3), 2, 2) + 3I, randn(sr(4), 2)),
            TestCase(\, rand(sr(6), 2, 2) + 3I, randn(sr(5), 2, 3)),
            TestCase(x -> all(>(0), x), randn(sr(7), 2); perf_flag=:allocs),
            TestCase(allunique, randn(sr(8), 2); perf_flag=:allocs),
            TestCase(x -> any(<(0), x), randn(sr(9), 2); perf_flag=:allocs),
            TestCase(append!, randn(sr(1), 3), randn(sr(0), 2)),
            TestCase(argmax, randn(sr(2), 2); perf_flag=:allocs),
            TestCase(argmin, randn(sr(3), 2)),
            TestCase(axes, randn(sr(4), 2, 1, 1, 2); perf_flag=:allocs),
            TestCase(circshift, randn(sr(5), 3), 1),
            TestCase(circshift!, randn(sr(6), 3), randn(sr(7), 3), 1; perf_flag=:allocs),
            TestCase(clamp!, randn(sr(8), 3), 0.0, 0.5; perf_flag=:allocs),
            TestCase(collect, randn(sr(9), 3)),
            TestCase(complex, randn(sr(1), 2)),
            TestCase(conj, randn(sr(2), 3)),
            TestCase(copy!, randn(sr(3), 2), randn(sr(4), 2)),
            TestCase(
                copyto!,
                randn(sr(5), 3),
                CartesianIndices(2:3),
                randn(sr(6), 2),
                CartesianIndices(1:2),
            ),
            TestCase(copyto!, randn(sr(7), 3), 2, randn(sr(8), 2), 1, 2),
            TestCase(copyto!, randn(sr(1), 3), randn(sr(2), 3)),
            TestCase(
                copyto!, PermutedDimsArray(randn(sr(7), 2, 3), [2, 1]), randn(sr(6), 3, 2)
            ),
            TestCase(x -> count(<(0), x), randn(sr(7), 2, 3); perf_flag=:allocs),
            TestCase(
                (r, A) -> count!(<(0), r, A),
                randn(sr(8), 2),
                randn(sr(9), 2, 3);
                perf_flag=:allocs,
            ),
            TestCase(cumprod, randn(sr(0), 3)),
            TestCase(
                (B, A) -> cumprod!(B, A; dims=2), randn(sr(1), 2, 2), randn(sr(2), 2, 2)
            ),
            TestCase(cumsum, randn(sr(3), 3)),
            TestCase(
                (out, v) -> cumsum!(out, v; dims=1),
                randn(sr(4), 3),
                randn(sr(5), 3);
                perf_flag=:allocs,
            ),
            TestCase(
                (out, v) -> cumsum!(out, v; dims=2), randn(sr(7), 2, 3), randn(sr(6), 2, 3)
            ),
            TestCase(deleteat!, randn(sr(8), 5), 3),
            TestCase(deleteat!, randn(sr(9), 5), 1),
            TestCase(deleteat!, randn(sr(0), 5), 5),
            TestCase(deleteat!, randn(sr(1), 5), 2:3),
            TestCase(deleteat!, randn(sr(2), 3), [false, true, true]),
            TestCase(deleteat!, randn(sr(3), 5), [1, 2, 5]),
            TestCase(diff, randn(sr(4), 5)),
            TestCase(x -> diff(x; dims=1), randn(sr(5), 3, 2)),
            TestCase(x -> diff(x; dims=2), randn(sr(6), 3, 2)),
            TestCase(empty, randn(sr(7), 5)),
            TestCase(extrema, randn(sr(8), 3); perf_flag=:allocs),
            TestCase(x -> extrema(sin, x), randn(sr(9), 3); perf_flag=:allocs),
            TestCase(x -> extrema(sin, x; dims=1), randn(sr(0), 3, 2)),
            TestCase(
                (r, A) -> extrema!(cos, r, A),
                tuple.(randn(sr(1), 3), randn(sr(2), 3)),
                randn(sr(3), 3, 2),
            ),
            TestCase(
                (r, A) -> extrema!(r, A),
                tuple.(randn(sr(4), 3), randn(sr(5), 3)),
                randn(sr(6), 3, 2),
            ),
            TestCase(fill!, randn(sr(7), 3), randn(sr(8)); perf_flag=:allocs),
            TestCase(fill!, randn(sr(0), 3, 2), randn(sr(9)); perf_flag=:allocs),
            TestCase(x -> filter(>(0), x), [0.5, -0.1, -0.4]),
            TestCase(x -> filter(<(0), x), randn(sr(1), 2, 2)),
            TestCase(x -> findall(<(0), x), [0.5, 0.1, -0.3]),
            TestCase(x -> findfirst(<(0), x), [0.5, -0.1, -0.4]; perf_flag=:allocs),
            TestCase(x -> findlast(<(0), x), [0.5, -0.1, -0.4]; perf_flag=:allocs),
            TestCase(findmax, randn(sr(1), 2, 2)),
            TestCase(x -> findmax(sin, x), [0.5, -0.1, -0.4]),
            TestCase(x -> findmax(sin, x), [0.5, -0.1, -0.4]),
            TestCase(findmin, randn(sr(2), 2, 2)),
            TestCase(x -> findmin(cos, x), randn(sr(3), 2, 2)),
            TestCase(first, randn(sr(4), 3); perf_flag=:allocs),
            TestCase(firstindex, randn(sr(5), 3); perf_flag=:allocs),
            TestCase(float, randn(sr(6), 3)),
            TestCase((x, i) -> get(_getter, x, i), randn(sr(7), 3), 2),
            TestCase((x, i) -> get(_getter, x, i), randn(sr(8), 3), 4),
            TestCase(getindex, randn(sr(9), 5), 1; perf_flag=:allocs),
            TestCase(getindex, randn(sr(0), 5), 3; perf_flag=:allocs),
            TestCase(getindex, randn(sr(1), 5, 4), 3; perf_flag=:allocs),
            TestCase(getindex, randn(sr(2), 5, 4), 2, 3; perf_flag=:allocs),
            TestCase(getindex, randn(sr(3), 5), 1:2),
            TestCase(getindex, randn(sr(4), 5), 2:4),
            TestCase(getindex, randn(sr(5), 5), :),
            TestCase(getindex, randn(sr(6), 3, 2), :),
            TestCase(getindex, randn(sr(7), 5), 1:2:5),
            TestCase(getindex, randn(sr(8), 5), [1, 3, 5]),
            TestCase(hash, randn(sr(9), 3, 4), UInt(2)),
            TestCase(hcat, randn(sr(0), 3, 2)),
            TestCase(hcat, randn(sr(1), 2, 3), randn(sr(2), 2, 2)),
            TestCase(imag, randn(sr(3), 2, 3)),
            TestCase(imag, randn(sr(4), ComplexF64, 2, 3)),
            TestCase(insert!, randn(sr(5), 3), 2, randn(sr(6))),
            TestCase(isassigned, randn(sr(7), 5), 3),
            TestCase(isassigned, randn(sr(8), 5), CartesianIndex(4)),
            TestCase(isempty, randn(sr(9), 5)),
            TestCase(isempty, randn(sr(0), 0)),
            TestCase(isequal, randn(sr(1), 3), randn(sr(2), 3)),
            TestCase(isreal, randn(sr(3), 3)),
            TestCase(isreal, randn(sr(4), ComplexF64, 3)),
            TestCase(iszero, randn(sr(5), 2)),
            TestCase(iterate, randn(sr(6), 2)),
            TestCase(iterate, randn(sr(7), 2, 2)),
            TestCase(keys, randn(sr(8), 2)),
            TestCase(keytype, randn(sr(9), 2)),
            TestCase(kron, randn(sr(0)), randn(sr(1), 2, 2)),
            TestCase(kron, randn(sr(3)), randn(sr(2), 2)),
            TestCase(kron, randn(sr(4), 2, 2), randn(sr(5))),
            TestCase(kron, randn(sr(7), 2), randn(sr(6))),
            TestCase(kron, randn(sr(8), 2), rand(sr(9), 3)),
            TestCase(kron, randn(sr(1), 2), randn(sr(0), 1, 2)),
            TestCase(kron, randn(sr(2), 2, 1), randn(sr(3), 3)),
            TestCase(kron, randn(sr(5), 2, 2), randn(sr(4), 2, 2)),
            TestCase(kron!, randn(sr(6), 2), randn(sr(7), 2), randn(sr(8))),
            TestCase(kron!, randn(sr(1), 2, 2), randn(sr(0), 2, 2), randn(sr(9))),
            TestCase(kron!, randn(sr(2), 2), randn(sr(3)), randn(sr(4), 2)),
            TestCase(kron!, randn(sr(7), 2, 2), randn(sr(6)), randn(sr(5), 2, 2)),
            TestCase(kron!, randn(sr(8), 6), randn(sr(9), 2), randn(sr(0), 3)),
            TestCase(kron!, randn(sr(3), 4, 3), randn(sr(2), 2), randn(sr(1), 2, 3)),
            TestCase(kron!, randn(sr(4), 4, 6), randn(sr(5), 2, 2), randn(sr(6), 2, 3)),
            TestCase(kron!, randn(sr(9), 3, 2), randn(sr(8), 1, 2), randn(sr(7), 3)),
            TestCase(kron!, randn(sr(0), 6, 2), randn(sr(1), 2, 2), randn(sr(3), 3, 1)),
            TestCase(last, randn(sr(4), 4)),
            TestCase(lastindex, randn(sr(5), 2)),
            TestCase(length, randn(sr(6), 2)),
            TestCase(length, randn(sr(7), 2, 3)),
            TestCase(map, sin, randn(sr(8), 2)),
            TestCase(map!, sin, randn(sr(9), 2), randn(sr(0), 2)),
            TestCase(map!, *, randn(sr(3), 2), randn(sr(2), 2), randn(sr(1), 2)),
            TestCase(mapreduce, sin, *, randn(sr(4), 2)),
            TestCase((f, x) -> mapslices(f, x; dims=1), sum, randn(sr(5), 2, 3)),
            TestCase(maximum, randn(sr(6), 2)),
            TestCase(maximum, randn(sr(7), 2, 3)),
            TestCase(maximum, sin, randn(sr(8), 2)),
            TestCase(maximum, cos, randn(sr(9), 2, 3)),
            TestCase(x -> maximum(cos, x; dims=2), randn(sr(0), 3, 2)),
            TestCase(maximum!, sin, randn(sr(2), 2), randn(sr(1), 2, 3)),
            TestCase(minimum, randn(sr(3), 2)),
            TestCase(minimum, randn(sr(4), 2, 3)),
            TestCase(minimum, sin, randn(sr(5), 2)),
            TestCase(minimum, cos, randn(sr(6), 2, 3)),
            TestCase(x -> minimum(cos, x; dims=2), randn(sr(7), 3, 2)),
            TestCase(minimum!, sin, randn(sr(9), 2), randn(sr(8), 2, 3)),
        ],
        vec(
            reduce(
                vcat,
                map(
                    Iterators.product(
                        [adjoint(randn(sr(0), 2, 3)), transpose(randn(sr(1), 2, 3))],
                        [randn(sr(3), 2), randn(sr(2), 2, 3)],
                        [randn(sr(4)), randn(sr(5), 1), randn(sr(6), 3)],
                    ),
                ) do (A, b, z)
                    TestCase(muladd, A, b, z)
                end,
            ),
        ),
        TestCase[
            TestCase(ndims, randn(sr(7), 2)),
            TestCase(ndims, randn(sr(8), 1, 2, 1, 1, 1)),
            TestCase(nextind, randn(sr(9), 3, 3), 2),
            TestCase(nextind, randn(sr(0), 3, 3), CartesianIndex(2, 2)),
            TestCase(pairs, randn(sr(1), 2, 2)),
            TestCase(parent, randn(sr(2), 3, 2)),
            TestCase(parentindices, randn(sr(3), 3, 2)),
            TestCase(permute!, randn(sr(5), 4), [2, 4, 3, 1]),
            TestCase(permutedims, randn(sr(6), 3, 2, 1), [2, 1, 3]),
            TestCase(permutedims, randn(sr(7), 2)),
            TestCase(permutedims, randn(sr(8), 2, 3)),
            TestCase(permutedims!, randn(sr(9), 2, 3, 1), randn(sr(0), 3, 2, 1), [2, 1, 3]),
            TestCase(pop!, randn(sr(1), 5)),
            TestCase(popat!, randn(sr(2), 5), 1),
            TestCase(popat!, randn(sr(4), 10), 5),
            TestCase(popat!, randn(sr(4), 5), 5),
            TestCase(popat!, randn(sr(5), 5), 7, 3.0),
            TestCase(popfirst!, randn(sr(6), 5)),
            TestCase(prepend!, randn(sr(7), 5), randn(sr(8), 3)),
            TestCase(prevind, randn(sr(9), 2, 3), 5),
            TestCase(prevind, randn(sr(0), 2, 3), CartesianIndex(2, 2)),
            TestCase(prod, randn(sr(1), 2)),
            TestCase(prod, randn(sr(2), 2, 3)),
            TestCase(x -> prod(x; dims=1), randn(sr(3), 2, 3)),
            TestCase(x -> prod(sin, x; dims=2), randn(sr(4), 2, 2)),
            TestCase(prod!, sin, randn(sr(6), 2), randn(sr(5), 2, 3)),
            TestCase(prod!, randn(sr(7), 2), randn(sr(8), 2, 3)),
            TestCase(promote_shape, randn(sr(0), 2), randn(sr(9), 2)),
            TestCase(promote_shape, randn(sr(1), 2), randn(sr(2), 2, 1, 1)),
            TestCase(push!, randn(sr(3), 5), 4.0),
            TestCase(pushfirst!, randn(sr(4), 5), 3.0),
            TestCase(real, randn(sr(5), 3, 2, 1)),
            TestCase(reduce, *, randn(sr(6), 2)),
            TestCase(reduce, *, randn(sr(7), 3, 2)),
            TestCase(repeat, randn(sr(8), 2), 2, 3),
            TestCase((x, i, o) -> repeat(x; inner=i, outer=o), randn(sr(9), 2), 2, 3),
            TestCase(reshape, randn(sr(0), 5), 1, 5),
            TestCase(reshape, randn(sr(0), 3, 2), 2, 3),
            TestCase(reshape, randn(sr(1), 3, 2), :, 3),
            TestCase(reshape, randn(sr(2), 3, 2), (6,)),
            TestCase(x -> (resize!(x, 10); x[6:end].=x[1:5]), randn(sr(3), 5)),
            TestCase(reverse, randn(sr(4), 3)),
            TestCase(reverse!, randn(sr(5), 3)),
            TestCase(reverseind, randn(sr(6), 5), 3),
            TestCase(selectdim, randn(sr(7), 3), 1, 2),
            TestCase(setdiff!, randn(sr(8), 3), randn(sr(9), 2)),
            TestCase(setindex!, randn(sr(0), 3), randn(sr(1)), 1),
            TestCase(setindex!, randn(sr(2), 3), randn(sr(3), 2), 1:2),
            TestCase(setindex!, randn(sr(4), 3), randn(sr(5)), CartesianIndex(2)),
            TestCase(setindex!, randn(sr(7), 3, 2), randn(sr(6)), 5),
            TestCase(setindex!, randn(sr(8), 3, 2), randn(sr(9)), 2, 2),
            TestCase(setindex!, randn(sr(0), 3, 2), randn(sr(1)), CartesianIndex(2, 1)),
            TestCase(setindex!, randn(sr(2), 3, 2), randn(sr(3), 2, 2), 2:3, 1:2),
            TestCase(setindex!, randn(sr(5), 3, 2), randn(sr(4), 2, 2), 1:2, :),
            TestCase(setindex!, randn(sr(6), 3, 2), randn(sr(7)), CartesianIndex(2), 1),
            TestCase(similar, randn(sr(8), 3, 2); interface_only=true),
            TestCase(size, randn(sr(9), 2)),
            TestCase(size, randn(sr(0), 3, 2)),
            TestCase(size, randn(sr(1), 3, 2, 1)),
            TestCase(sizeof, randn(sr(2), 5)),
            TestCase(sort, randn(sr(3), 3)),
            TestCase(sort!, randn(sr(4), 3)),
            TestCase(sortperm, randn(sr(0), 3)),
            TestCase(sortperm!, [1, 2, 3], randn(sr(1), 3)),
            TestCase(x -> sortslices(x; dims=1), randn(sr(2), 2, 3)),
            TestCase(splice!, randn(sr(5), 5), 1:2),
            TestCase(splice!, randn(sr(6), 5), 1:0),
            TestCase(splice!, randn(sr(7), 5), 1:5),
            TestCase(splice!, randn(sr(8), 5), 1:2, randn(sr(6), 3)),
            TestCase(splice!, randn(sr(9), 5), 3:2, randn(sr(5), 4)),
            TestCase(splice!, randn(sr(0), 5), 1),
            TestCase(splice!, randn(sr(1), 5), 1, randn(sr(3))),
            TestCase(splice!, randn(sr(2), 5), 1, randn(sr(4), 3)),
            TestCase(stride, randn(sr(7), 3, 2), 1),
            TestCase(sum, randn(sr(8), 2, 3)),
            TestCase(x -> sum(x; dims=1), randn(sr(9), 3, 2)),
            TestCase((f, x) -> sum(f, x; dims=2), sin, randn(sr(0), 3, 2)),
            TestCase(sum!, randn(sr(2), 1, 3), randn(sr(1), 2, 3)),
            TestCase(sum!, sin, randn(sr(3), 1, 3), randn(sr(4), 2, 3)),
            TestCase(transpose, randn(sr(5), 3)),
            TestCase(transpose, randn(sr(6), 3, 2)),
            TestCase(transpose, randn(sr(7), 1, 3)),
            TestCase(unique, randn(sr(8), 3)),
            TestCase(valtype, randn(sr(9), 3)),
            TestCase(vcat, randn(sr(0), 2)),
            TestCase(vcat, randn(sr(1), 2, 2)),
            TestCase(vcat, randn(sr(2), 3), randn(2)),
            TestCase(vcat, randn(sr(3), 3, 2), randn(sr(4), 2, 2)),
            TestCase(vec, randn(sr(5), 2)),
            TestCase(vec, randn(sr(6), 2, 3)),
            TestCase(view, randn(sr(7), 2, 3), 1:2, 1:2),
            TestCase(view, randn(sr(8), 3, 2), 1:3),
            TestCase(view, randn(sr(9), 3, 2), :, 1),
            TestCase(view,randn(sr(0), 3, 2),:,:),
            TestCase(zero, randn(sr(1), 3)),
            TestCase(zero, randn(sr(2), 2, 3)),
        ],
    )
    for (tc, name) in zip(test_cases, Mooncake.TestUtils._test_case_names(test_cases))
        @info name
        test_rule(sr(123456), tc; fallbacks=(is_primitive=false,), name)
    end

    # A mixed-eltype `copyto!` reaches `jl_array_ptr` on 1.10, which refuses widths > 1.
    # On 1.11+, `MemoryRef` supports every width, so restrict only the legacy path.
    test_cases = [
        TestCase(
            copyto!,
            randn(sr(1), ComplexF64, 3),
            2,
            randn(sr(12), 2),
            1,
            2;
            skip_chunked=(VERSION < v"1.11-"),
        ),
        TestCase(
            copyto!,
            randn(sr(4), ComplexF64, 1, 3),
            randn(sr(5), 1, 3);
            skip_chunked=(VERSION < v"1.11-"),
        ),
    ]
    for (tc, name) in zip(test_cases, Mooncake.TestUtils._test_case_names(test_cases))
        @info name
        test_rule(sr(123456), tc; fallbacks=(is_primitive=false,), name)
    end

    # When the inner function of Base._growend! is reached,
    # parameter `a` had its size increased before the underlying memory was reallocated,
    # which causes a segfault in debug mode when validating the tangent.
    # This is worked around in __verify_fdata_value,
    # and this test ensures that the workaround is effective.
    # This was only a problem in Julia v1.11, but push! should anyway work on all versions.
    @testset "push! in debug mode" begin
        test_rule(
            sr(123456), push!, [[1.0, 2.0]], [3.0, 4.0]; is_primitive=false, debug_mode=true
        )
    end
end
