env:
  SECRET_CODECOV_TOKEN: "OQDm6ItKZvxShVmPvjHQjJsCg0tbXqkAE6iEJAT/pD9q6kxlgmEywlf3atV4puF7YkydNDrNivL2uhqy8QoK/bKJrW0wHQ7+9F1Q3NZg/OOkAIRZxDg5+90E7ucJwquk04iEq0W4sD5D4XXeKLRUe+vs0+kmID+Pe6L2i+K2UOAkPJ/JHPgvFzPUv3lbEt0qhv81hn9qtE3wrlp4SbsQWMbKixFSftdWm7Op8+mBA55pjoq+PVI2FOksFjsM/zSBvQn+oJbz6OVi7BRDr5LFm59DOMv/udKkE1YbkNCxL5ao4YeGIq+vJwJbLwAC74ZIeHcPpoFQAccburSue/JYJA==;U2FsdGVkX19J5BVBerBpwP0M6aA4aGNFV8QPDoP2/0EnM+4xawaahn2AkCfjf0ZJ9sB2KEJZLhz2BAxpNhh+pTRtPwehvfnpDWEtAMJTjWs="

steps:
  - label: "Julia v1"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          dirs:
            - src
            - ext
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 60
    env:
      TEST_GROUP: "gpu"
