@testset "twice_precision" begin
    rng = sr(123)
    p = Base.TwicePrecision{Float64}(5.0, 4.0)
    a = TwicePrecision(1.0, 0.0)
    b = TwicePrecision(1.0 + 1e-10, 0.0)
    @test has_equal_data(a, b)
    @test !has_equal_data(a, b; exact_floats=true)
    @test !has_equal_data(a, TwicePrecision(1.0, 1e-20); exact_floats=true)
    @test has_equal_data(a, a; exact_floats=true)
    @test !has_equal_data(a, TwicePrecision(1.00001, 0.0))
    @test has_equal_data(a, TwicePrecision(1.00001, 0.0); float_precision=Float32)
    TestUtils.test_tangent_interface(rng, p)
    TestUtils.test_tangent_splitting(rng, p)
    TestUtils.test_lifted(rng, p)
    TestUtils.run_rule_test_cases(StableRNG, Val(:twice_precision))
end
