name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  schedule:
    - cron:  '28 0,6,12,18 * * *'
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: ${{ matrix.test_group }}
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule'
    strategy:
      fail-fast: false
      matrix:
        test_group:
          - 'basic'
          - 'integration_testing/misc'
          - 'integration_testing/diff_tests'
          - 'integration_testing/distributions'
          - 'integration_testing/special_functions'
          - 'integration_testing/array'
          - 'integration_testing/turing'
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
          arch: x64
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          TEST_GROUP: ${{ matrix.test_group }}
  perf:
    name: "Performance (${{ matrix.perf_group }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perf_group:
          - 'hand_written'
          - 'derived'
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
          arch: x64
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - run: julia --project=benchmarking --eval 'include("benchmarking/run_benchmarks.jl")'
        env:
          PERF_GROUP: ${{ matrix.perf_group }}
        shell: bash
