name: Automatically assign PR authors

on:
  pull_request:
    types:
      - opened

permissions:
  pull-requests: write

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: TuringLang/actions/PRAssign@main
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
